### ISSUE TITLE
Structure of .h5 file

### ISSUE THREAD

**Issue by shenxiaolu1984** [anewell/pose-hg-train#1]
Hi, anewell,

Thank you for sharing the code! It's great help for me to understand the network structure.

Under '/data/mpii/annot/', 'Datasets' for test.h5, valid.h5 and train.h5 are different. What they have in common are:
1-center
2-imgname
3-index
4-normalize
5-part
6-person
7-scale
8-torsoangle
9-visible

I'm trying to fine-tune with my own data. What datasets should I provide in the .h5 file? And what's the meaning of them?

**Comment by anewell** [comment]
I've added an example script in src/misc for generating the .h5 file using the MPII annotations, let me know if that helps! (It doesn't do the training/validation split)

Most of the data is directly copied over from the MPII annotations. Torso angle for example is something I threw in, it just measures the angle from the pelvis to the neck. It is currently not used anywhere in the code here, but it is useful for doing some extra analysis.

**Comment by shenxiaolu1984** [comment]
Thanks! It's very helpful for understanding the structure!
