### ISSUE TITLE
Using nn.gModule

### ISSUE THREAD

**Issue by wydges** [anewell/pose-hg-train#14]
I have another question, I'm new to machine learning, and especially to torch. Why you wrapped your model with nn.gModule, neither than nn.Module. What is the difference?

**Comment by yangky11** [comment]
`nn.gModule` is in a torch package named nngraph, it encapsulates a computational graph into a `nn.Module`-compatible module on which you can invoke `forward` and `backward` . 
Check out [nngraph](https://github.com/torch/nngraph)
