### ISSUE TITLE
Evaluation on MPII Human Pose Dataset

### ISSUE THREAD

**Issue by Litchiware** [anewell/pose-hg-train#18]
Hi, @anewell, I want to use the evaluation script `evaluatePCKh.m` downloaded on [MPII Human Pose Dataset](http://human-pose.mpi-inf.mpg.de/#download) to measure my model's performance, but I could not find the `annolist_dataset_v12.mat` file loaded in this line of the script.
```
load([p.gtDir '/annolist_dataset_v12'],'annolist');
```
Do you know how to get this file, thanks.

**Comment by anewell** [comment]
You can get that file from the MPII website from the download page you linked - "Annotations (12.5 MB)"

**Comment by anewell** [comment]
Oh sorry, I wasn't paying attention, that's not my code actually, so not sure what that file is referring to.

You can also use the python code in this repository under src/pypose to do evaluation. (Edit: actually maybe not a great idea to use that code at the moment, it hasn't been updated to work with recent changes, instead check out the evaluation code in the other repository pose-hg-demo)

**Comment by Litchiware** [comment]
Thanks for your reply. I think I can use `pose-hg-train/src/misc/predictMPII.m` to generate `pred_keypoints_mpii.mat`, and send this file to MPII dataset team and get evaluation results from them, right?

**Comment by anewell** [comment]
Yep, you can do that. The file 'predictMPII.m' needs to be updated a little bit, just a small modification to read in the predictions properly. I will push that in a little bit.

In general, it is good to make sure that you can also do evaluation on validation predictions since you don't want to submit predictions on the official MPII test set too often.

**Comment by Litchiware** [comment]
Thanks a lot, I think this issue can be closed.
