### ISSUE TITLE
-task'pose-int' vs 'pose' 

### ISSUE THREAD

**Issue by shenxiaolu1984** [anewell/pose-hg-train#2]
Hi anewell,

Thanks again for the update!

When set -task from 'pose-int'  to 'pose', (not using intermediate supervision) the training goes wrong.
Similar situation when set -nStack to 1.

I guess somewhere when the program anticipates a sequence of length 1, it gets a tensor instead.

Is there any quick fix to this?

Thanks!

**Comment by anewell** [comment]
Did you run with the 'no-int' version of the model? And yeah, there's a quick fix for the '-nStack 1' issue, it will be fixed in a commit that takes care of some other issues and includes an improved version of the model that I'll push in a couple weeks.

**Comment by shenxiaolu1984** [comment]
Thanks anewell! Looking forward to that!

**Comment by shenxiaolu1984** [comment]
Hi, anewell,
Any news about the '-nStack 1' issue? :)

**Comment by anewell** [comment]
Sorry, I realize a "couple weeks" somehow turned into months. Updating the code got pushed back for a variety of reasons, and then I got caught up in a big project and this fell to the wayside. I'll try to update the repository soon!
