### ISSUE TITLE
Head and Shoulder are not included in computing the accuracy

### ISSUE THREAD

**Issue by zhiqiangdon** [anewell/pose-hg-train#26]
Hi @anewell ,

I am reading your code and find the accuracy of MPII dataset is computed only based on these predefined joints " self.accIdxs = {1,2,3,4,5,6,11,12,15,16}". In your paper, joints of Head, Shoulder, Elbow, Wrist, Hip, Knee and Ankle are reported. It seems Head and Shoulder are missing in "self.accIdxs". Could you explain why?

**Comment by anewell** [comment]
The accuracy indices are used for reporting an average accuracy term when running experiments. This term is mostly an approximation and not used to report final performance numbers. The main reason for leaving out the head and shoulders here is that the accuracy for those parts gets very high, very quickly, and without them it is easier to distinguish the performance of different experiments.

**Comment by zhiqiangdon** [comment]
Thanks @anewell . It makes sense.
