### ISSUE TITLE
gaussian kernel size

### ISSUE THREAD

**Issue by fiarabbit** [anewell/pose-hg-train#31]
Sigma of Gaussian used as the target of MSE criterion might be 0.25, despite 1px described in the article.

See:
src/util/img.lua Line 214
`local g = image.gaussian(size)`

['image'](https://github.com/torch/image/blob/master/doc/tensorconstruct.md)

>  The default value of the horizontal and vertical standard deviation sigma_horz and sigma_vert of the Gaussian kernel is sigma, where the latter has a default value of 0.25.

**Comment by anewell** [comment]
The sigma value is a function of the kernel size, but you're right it doesn't quite match up with the paper. You can check out the comments in this issue: https://github.com/anewell/pose-hg-train/issues/25

**Comment by fiarabbit** [comment]
Thanks for reply! I clearly understand the point now.
