### ISSUE TITLE
What does the 'modelArgs' mean?

### ISSUE THREAD

**Issue by wangg12** [anewell/pose-hg-train#5]
`modelArgs` is in `createModel(modelArgs)` in the file `model.lua`. However, I can not find its definition.
By the way, how can I create a model with fake input data from scratch? I can not figure it out.

**Comment by anewell** [comment]
`modelArgs` is a remnant from older versions of the code, it would often be defined in the opt.task file, but in the current version of the code it's not necessary, just there for backwards compatibility with some old projects of mine

**Comment by wangg12** [comment]
@anewell Thanks for your reply.
