### ISSUE TITLE
meaning of imgname in annot.h5

### ISSUE THREAD

**Issue by Jugaris89** [anewell/pose-hg-train#50]
Hi,

great work!

I don't fully understand what is what you write as imgname in annot.h5. I am training with my own dataset and I am not quite sure what shall be there specified.

right now, in you code, it looks like: 
   DATASET "imgname" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 40614, 16 ) / ( 40614, 16 ) }
      DATA {
      (0,0): 48, 51, 55, 52, 53, 52, 48, 49, 50, 46, 106, 112, 103, 0, 0, 0,

which does not correspond to the names of the images. How shall they be interpreted?

thanks in advance
Javier

**Comment by anewell** [comment]
Hi Javier,

Those actually are the image filenames, I had to encode them like that because there were issues saving strings in the hdf5 file. If you want to parse the string check out the line here: https://github.com/umich-vl/pose-hg-train/blob/master/src/util/dataset/mpii.lua#L81

Hope that helps!
Alejandro

**Comment by Jugaris89** [comment]
thank you for your answer. 

one last question, which is the difference between the notation in h5 file of "person" and "center" ? I understood center are the 2D coordinates of the joints but then person I don't fully understand

Could you clarify me this last question plz?

thanks in advance

**Comment by Jugaris89** [comment]
ok just saw in MPII dataset the following
id - joint id (0 - r ankle, 1 - r knee, 2 - r hip, 3 - l hip, 4 - l knee, 5 - l ankle, 6 - pelvis, 7 - thorax, 8 - upper neck, 9 - head top, 10 - r wrist, 11 - r elbow, 12 - r shoulder, 13 - l shoulder, 14 - l elbow, 15 - l wrist)

this is what's meant in "person" annotation in the h5 file right? to which joint refers the center annotation, right?

**Comment by Jugaris89** [comment]
can you tell me please how did you create your "person" group ?

I have created mine with matlab using "h5create" and "h5write" and I get following error when trying to train:

mpii.lua:36: inconsistent tensor size, expected tensor [1] and src [40614] to have the same number of elements, but got 1 and 40614 elements respectively at /mnt/md0/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:121

seems like I did sth wrong when creating the dataset. What I did was, create in matlab a row-vector with the notation i needed for person and then create a h5 file from it.

could u help me plz?

thanks
