### ISSUE TITLE
usage of visualize_results

### ISSUE THREAD

**Issue by Jugaris89** [anewell/pose-hg-train#52]
Hi,

I have a short question regarding the usage of the lua-file for visualizing results "misc/visualize_results.lua"

This file is expecting you to store your predictions in exp/mpii/best

is this "best" file and "best_preds" automatically generated when validating your net? When is the group "pred_heatmap" generated in the preds.h5? I have not been able to find this on the code

Thank you very much in advance

**Comment by anewell** [comment]
Hi,

I can't guarantee that the code in visualize_results is compatible with the rest of the code as it was written at a different time. It seemed better to leave it in as a reference than to remove it altogether.

I don't really remember when best/best_preds are generated, but you can probably plug in paths to any other prediction file. As for the heatmaps, there's an [additional command line option](https://github.com/umich-vl/pose-hg-train/blob/master/src/opts.lua#L34) to include heatmaps when [saving predictions](https://github.com/umich-vl/pose-hg-train/blob/master/src/train.lua#L67) "-saveHeatmaps", but you might need to tweak the code in visualize_results.lua a bit for it all to work.

**Comment by Jugaris89** [comment]
thanks for your reply!

what is exactly saved when enabling "saveHeatmaps" options, because I am training with this option as true and no maps are being stored apparently. 

I have tried running the file and pointint to the preds.h5 file generated when "th main.lua -branch your-exp -expID final-preds -finalPredictions -nEpochs 0" but the file looks for groups that I don't know where are they created. 

is it correct that I use it with the generated preds.h5 or shall I generate the h5 file with the prediction somehow else? what is being stored with the option "saveHeatmaps" activated?

thanks again
