### ISSUE TITLE
Memory consumption of the model

### ISSUE THREAD

**Issue by yxchng** [anewell/pose-hg-train#6]
Hi, I am trying to implement your code in theano and I am bumping into memory problems. Can I know how much memory does your model takes on the GPU? I am using Titan X as well. Thanks.

**Comment by anewell** [comment]
Typically during training I can fit a batchsize of 8 on a Titan X, so the model does require quite a bit of memory.

**Comment by yxchng** [comment]
Hi, I notice that your architecture in v2 paper and the architecture in this code are different. I intend to implement the v2 architecture.

In v1, right before the hourglass and after the initial maxpooling, you have 3 residual modules but it seems like you have 2 in v2. And so just to verify, is this correct?

``` python
    inputs = Input((3, 256, 256))
    conv1 = ZeroPadding2D((3,3))(inputs)
    conv1 = Convolution2D(64, 7, 7, border_mode = 'valid', subsample = (2, 2))(conv1)
    conv1 = BatchNormalization(mode = 0, axis = 1)(conv1)
    conv1 = Activation('relu')(conv1)
    r1 = _residual_block(128)(conv1)
    pool = MaxPooling2D(pool_size = (2, 2), strides = (2, 2))(r1)
    r5 = _residual_block(128)(pool)
    r6 = _residual_block(256)(r5)
```

On top of that after each hourglass, the paper says 2 1x1 are fitted to produce the heatmaps and so this is what I did:

``` python
    hg1 = _hourglass(4, 256)(r6)
    l1 = _conv_bn_relu(256)(hg1)
    l1_ = Convolution2D(256, 1, 1, border_mode = 'valid', subsample = (1, 1))(l1)
    out1 = Convolution2D(16, 1, 1, border_mode = 'valid', subsample = (1, 1))(l1)
    out1_ = Convolution2D(256, 1, 1, border_mode = 'valid', subsample = (1, 1))(out1)
    sum1 = merge([r6, l1_, out1_], mode = 'sum')
```

Is the concatenation (sum1) correct as well, meaning that it is summing the input to the hourglass, the output of the hourglass after 2 1x1 convolution and a 1x1 convolution of the heatmap?

Throughout the entire architecture, the max number of filters are 256, right?

I would really appreciate if you can verify the architecture. I am having trouble figuring some small details from the paper alone.

**Comment by yxchng** [comment]
Also, can I know if you are also using this same training options for v2?

```
cmd:option('-nEpochs',           100, 'Total number of epochs to run')
cmd:option('-trainIters',       4000, 'Number of train iterations per epoch')
cmd:option('-trainBatch',          6, 'Mini-batch size')
cmd:option('-validIters',       2958, 'Number of validation iterations per epoch')
cmd:option('-validBatch',          1, 'Mini-batch size for validation')
```

I can't fit this into my GPU without memory error.

**Comment by anewell** [comment]
I've just pushed a long overdue update to the repository, it includes the updated model file, so hopefully should clear up any confusion. Let me know if you have any further questions!
