### ISSUE TITLE
Image crop out of range during MPII training

### ISSUE THREAD

**Issue by gulvarol** [anewell/pose-hg-train#8]
Thanks for releasing the code! It is really helpful.

I tried the training on MPII and after 7 epochs it gave an error for the image cropping being out of range:

```
==> Starting epoch: 8/100
... pose-hg-train/src/util/img.lua:107: bad argument #6 to 'sub' (out of range...
```

Do you have any guess why this would happen?

**Comment by anewell** [comment]
I think it's a little indexing bug which I introduced in the newer version of the code. I added a simple check that should catch it, but I'll look into it further to ensure everything's all good. If that doesn't take care of the issue, I've also brought back the old cropping function as a back up which should work as well.

Hope that helps!

**Comment by gulvarol** [comment]
The new version of the code seems to have solved the issue. The training has ran many more epochs and didn't crash.

Thanks!
