### ISSUE TITLE
Can I know if you are passing image as float or integer into the network?

### ISSUE THREAD

**Issue by yxchng** [anewell/pose-hg-train#9]
I am still having problems with memory and am wondering if you pass images as float or integer into the network? Thanks.

**Comment by anewell** [comment]
Hi, so I realized that the current version of the model actually only fits a batch size of 6 (which still trains fine) as opposed to 8 which is the default setting. So, see if a batch size of 6 works for you (on a 12 GB Titan X). You can also make the network smaller setting nStack as low as 4 and not lose much performance.

To answer your question, images are passed in as floats, all tensors during training are stored as 32-bit floats. Though it looks like Torch recently introduced the option for a "halfTensor" which uses 16 bit floats instead and that would be interesting to experiment with.

**Comment by yxchng** [comment]
ok i will try with batch size 6
